services:
  webShuffle: #8443
    image: sequence-track-player:v10
    container_name: web_shuffle_nonprod_9
    volumes:
      - /smb/ssd/Radio/FULLY_PROCESSED/:/mnt/p/VOX/FULLY_PROCESSED/
      - /var/lib/docker/volumes/self-signed/_data/:/etc/ssl/certs/java/carts/
    restart: unless-stopped
    ports:
      - 192.168.181.24:85:8443